<?php

namespace otakuProject\nendoroidBundle\Repository;

/**
 * rangeNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rangeNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
