otaku_projectnendoroid:
    resource: "@otakuProjectnendoroidBundle/Resources/config/routing.yml"
    prefix:   /nendoroid

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'