# views

nendoroids_list:
    path: /list
    defaults:
      _controller: otakuProjectnendoroidBundle:Nendoroid:nendoroidsList

user_profil:
    path: /user/{username}
    defaults:
      _controller: otakuProjectnendoroidBundle:Nendoroid:userProfil

# get data

get_nendoroids:
  path: /get/nendoroids
  defaults:
    _controller: otakuProjectnendoroidBundle:Nendoroid:getNendoroids
    methods: [post]

get_users:
  path: /get/users
  defaults:
    _controller: otakuProjectnendoroidBundle:Nendoroid:getUsers
    methods: [post]

get_user_lists:
    path: /get/lists
    defaults:
      _controller: otakuProjectnendoroidBundle:Nendoroid:getUserLists
      methods: [post]

search_nendoroid_ajax:
  path: /search
  defaults:
    _controller: otakuProjectnendoroidBundle:Nendoroid:searchAjax
    methods: [post]

# add/remove lists

nendoroid_ajax:
  path: /listNendo
  defaults:
    _controller: otakuProjectnendoroidBundle:Nendoroid:nendoroidAjax
    methods: [post]
